Capture stdout and stderr when quiet is on (#96)
Example usage: `stack-pr submit` returned with exit 1 due to an outdated version of `gh`.

```
$ stack-pr submit

Adding cross-links to PRs
Exitcode: 1
Stdout: None
Stderr: GraphQL: Projects (classic) is being deprecated in favor of the new Projects experience, see: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/. (repository.pullRequest.projectCards)

subprocess.CalledProcessError: Command '['gh', 'pr', 'edit', 'https://github.com/modularml/modular/pull/70936', '-t', 'Test GH', '-F', '-', '-B', 'main']' returned non-zero exit status 1.
```

Test Plan:

```
python -m pytest tests/test_shell_commands.py -v
```